version: '3'
networks:
  test-network:
    external: true

services:
  db:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - '5433:5433'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - test-network

  app1:
    image: server_app
    container_name: app_1
    build: .
    ports:
      - '3002:3000'
    environment:
      - SERVER_PORT=3002
      - DATABASE_URL=postgres://postgres:postgres@db:5433/myapp
    depends_on:
      - db
    networks:
      - test-network

  app2:
    image: server_app
    container_name: app_2
    build: .
    ports:
      - '3003:3000'
    environment:
      - SERVER_PORT=3003
      - DATABASE_URL=postgres://postgres:postgres@db:5433/myapp
    depends_on:
      - db
    networks:
      - test-network

volumes:
  postgres-data:
