version: '3'
networks:
  test-network:
    external: true

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    build:
      context: .
    ports:
      - '80:80'
    networks:
      - test-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
